### ISSUE TITLE
Problem with creating bucket for file preview

### ISSUE THREAD

**Issue by pli888** [rija/gigadb-website#10]
When creating a S3 bucket using `/vagrant/protected/yiic createbucket --fromconfig`, I get an error:
```
Creating bucket for preview functionality: fpreviews_test
PHP Error[2]: include(/vagrant/protected/config/../vendors/aws/Aws/S3/Waiter/BucketExists.php): failed to open stream: No such file or directory
    in file /opt/yii-1.1.16/framework/YiiBase.php at line 438
```

I have to comment out line 46 in `protected/commands/CreateBucketCommand.php` to not see this error. The bucket is created though.

**Comment by rija** [comment]
I've managed to reproduce the error (running the create bucket command to create a non-existing preview bucket from config). I will look at the issue. 

```
[vagrant@ftp-server ~]$ /vagrant/protected/yiic createbucket --fromconfig


array(1) {
  ["fromconfig"]=>
  string(0) ""
}
Creating bucket for preview functionality: gigadb-bundles-test2
PHP Error[2]: include(/vagrant/protected/config/../vendors/aws/Aws/S3/Waiter/BucketExists.php): failed to open stream: No such file or directory
    in file /opt/yii-1.1.16/framework/YiiBase.php at line 438
#0 /opt/yii-1.1.16/framework/YiiBase.php(438): autoload()
#1 unknown(0): autoload()
#2 unknown(0): spl_autoload_call()
#3 /vagrant/protected/vendors/aws/Aws/Common/Waiter/WaiterClassFactory.php(99): class_exists()
#4 /vagrant/protected/vendors/aws/Aws/Common/Waiter/WaiterClassFactory.php(81): Aws\Common\Waiter\WaiterClassFactory->getClassName()
#5 /vagrant/protected/vendors/aws/Aws/Common/Waiter/CompositeWaiterFactory.php(83): Aws\Common\Waiter\WaiterClassFactory->canBuild()
#6 /vagrant/protected/vendors/aws/Aws/Common/Waiter/CompositeWaiterFactory.php(44): Aws\Common\Waiter\CompositeWaiterFactory->getFactory()
#7 /vagrant/protected/vendors/aws/Aws/Common/Client/AbstractClient.php(215): Aws\Common\Waiter\CompositeWaiterFactory->build()
#8 /vagrant/protected/vendors/aws/Aws/Common/Client/AbstractClient.php(208): Aws\S3\S3Client->getWaiter()
#9 /vagrant/protected/commands/CreateBucketCommand.php(46): Aws\S3\S3Client->waitUntil()
#10 /opt/yii-1.1.16/framework/console/CConsoleCommandRunner.php(71): CreateBucketCommand->run()
#11 /opt/yii-1.1.16/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#12 /opt/yii-1.1.16/framework/base/CApplication.php(184): CConsoleApplication->processRequest()
#13 /opt/yii-1.1.16/framework/yiic.php(33): CConsoleApplication->run()
#14 /vagrant/protected/yiic.php(8): require_once()
#15 /vagrant/protected/yiic(4): require_once()
[vagrant@ftp-server ~]$ 
```

**Comment by pli888** [comment]
The above [commit](https://github.com/rija/gigadb-website/commit/20c588f6bd5521bdc9e4c040f59dfd501e583832) has fixed this issue.
